tracked:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  base2FL_position_controller:
    type: position_controllers/JointPositionController
    joint: base2FL
    pid: {p: 50.0, i: 0.01, d: 10.0}
  base2RL_position_controller:
    type: position_controllers/JointPositionController
    joint: base2RL
    pid: {p: 50.0, i: 0.01, d: 10.0}
  base2FR_position_controller:
    type: position_controllers/JointPositionController
    joint: base2FR
    pid: {p: 50.0, i: 0.01, d: 10.0}
  base2RR_position_controller:
    type: position_controllers/JointPositionController
    joint: base2RR
    pid: {p: 50.0, i: 0.01, d: 10.0}
  base2m1_position_controller:
    type: effort_controllers/JointEffortController
    joint: base2m1
    pid: {p: 80.0, i: 0.01, d: 10.0}
  joint1_position_controller:
    type: effort_controllers/JointEffortController
    joint: joint1
    pid: {p: 80.0, i: 0.01, d: 10.0}
  joint2_position_controller:
    type: effort_controllers/JointEffortController
    joint: joint2
    pid: {p: 80.0, i: 0.01, d: 10.0}
