<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="tracked" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <joint name="base2m1" type="continuous">
    <parent link="base"/>
    <child link="m1"/>
    <origin xyz="0 0 ${l_bh/2}" rpy="0 0 ${PI}"/>
    <axis xyz="0 0 1"/>
<!--    <limit lower="${-PI}" upper="${PI}" effort="1" velocity="1" />-->
    <dynamics damping="0.7"/>
  </joint>

  <link name="m1">
    <collision>
      <origin xyz="0 0 ${m_h/2}" rpy="0 0 0"/>
      <geometry>
	<mesh filename="package://tracked_description/meshes/motor_a.stl"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${m_h/2}" rpy="0 0 0"/>
      <geometry>
	<mesh filename="package://tracked_description/meshes/motor_a.stl"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${m_h/2}" rpy="0 0 0"/>
      <mass value="${m_1}"/>
      <inertia
	  ixx="0.000907922" ixy="0.0" ixz="0.0"
	  iyy="0.007360669" iyz="0.0"
	  izz="0.006719413"/>
    </inertial>
  </link>

  <joint name="joint1" type="continuous">
    <parent link="m1"/>
    <child link="link2"/>
    <origin xyz="0 0 ${m_h}" rpy="0 0 0"/>
    <axis xyz="0 -1 0"/>
<!--    <limit lower="${-PI}" upper="${PI}" effort="1" velocity="1" />-->
    <dynamics damping="0.7"/>
  </joint>

  <!-- Middle Link -->
  <link name="link2">
    <collision>
      <origin xyz="0 0 ${height2/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height2}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height2/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height2}"/>
      </geometry>
      <material name="grey"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height2/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height2*height2)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height2*height2 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="joint2" type="continuous">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="0 0 ${height2}" rpy="0 0 0"/>
    <axis xyz="0 -1 0"/>
<!--    <limit lower="${-PI}" upper="${PI}" effort="1" velocity="1" />-->
    <dynamics damping="0.7"/>
  </joint>

  <!-- Top Link -->
  <link name="link3">
    <collision>
      <origin xyz="0 0 ${height3/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height3}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height3/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height3}"/>
      </geometry>
      <material name="grey"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height3/2}" rpy="0 0 0"/>
      <mass value="${0.3}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height3*height3)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height3*height3 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="link3_2camera2" type="fixed">
    <parent link="link3"/>
    <child link="camera2"/>
    <origin xyz="0.05 0 0.3" rpy="${PI} ${PI/2} ${PI}"/>
  </joint>

  <link name="camera2">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
      <material name="red"/>
    </visual>
  </link>


  <joint name="link3_2camera1" type="fixed">
    <origin xyz="0.05 0 0" rpy="${PI} ${PI/2} ${PI}"/>
    <parent link="link3"/>
    <child link="camera1"/>
  </joint>

  <!-- Camera -->
  <link name="camera1">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
      <material name="red"/>
    </visual>
  </link>

  <!-- generate an optical frame http://www.ros.org/reps/rep-0103.html#suffix-frames
      so that ros and opencv can operate on the camera frame correctly -->
  <joint name="camera1_optical_joint" type="fixed">
    <!-- these values have to be these values otherwise the gazebo camera image
        won't be aligned properly with the frame it is supposedly originating from -->
    <origin xyz="0 0 0" rpy="${0} ${0} ${PI}"/>
    <parent link="camera1"/>
    <child link="camera1_optical"/>
  </joint>

  <link name="camera1_optical">
  </link>


  <joint name="camera2_optical_joint" type="fixed">
    <!-- these values have to be these values otherwise the gazebo camera image
        won't be aligned properly with the frame it is supposedly originating from -->
    <origin xyz="0 0 0" rpy="${0} ${0} ${PI}"/>
    <parent link="camera2"/>
    <child link="camera2_optical"/>
  </joint>

  <link name="camera2_optical">
  </link>


  <transmission name="tran_base2m1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="base2m1">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_base2m1">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran_joint1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_joint1">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran_joint2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_joint2">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>
